### ISSUE TITLE
Squid chart configmap not respecting right indentation

### ISSUE THREAD

**Issue by sebastien-prudhomme** [honestica/lifen-charts#12]
The `labels` block is not correctly indented, should be:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "squid.fullname" . }}-conf
  labels:
    app: {{ template "squid.name" . }}
    chart: {{ template "squid.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  squid.conf: |
{{ .Values.config | indent 4 }}
```
