### ISSUE TITLE
kube-iptables-tailer install fails with error "server cannot find the resource projectcalico.org/v3/GlobalNetworkPolicy"

### ISSUE THREAD

**Issue by Leke-Ariyo** [honestica/lifen-charts#69]
I installed kube-iptables-tailer via its chart and synced on argocd but sync failed with the message
```server cannot find the resource projectcalico.org/v3/GlobalNetworkPolicy```

we have calico 3.22 - installed by tigera-operator - and can only see CRDs with v1 - so how come docs say v3 ?

**Comment by mtparet** [comment]
Hum this is weird indeed, could give the command/files you launch to install calico and kube iptable tailer ?

**Comment by Leke-Ariyo** [comment]
I used the chart in https://github.com/honestica/lifen-charts/tree/master/kube-iptables-tailer to setup the kube-iptables-tailer chart and https://github.com/projectcalico/calico/tree/master/calico/_includes/charts/tigera-operator for calico chart and They are applied in the gitops way (Argocd)

It seems some have working v3 GlobalNetworkPolicy https://github.com/honestica/lifen-charts/
but this does not work with our latest calico currently.

Or perhaps there is a part of calico I am missing?

This is my Environment:
    Calico version: v3.22
    kubernetes: 1.22
    Operating System and version: Ubuntu 20.04.3 LTS

**Comment by KlavsKlavsen** [comment]
We also have a setup on AWS - setup by KOPS (k8s v1.20 currently - updating soon) - and it has the EXACT same problem - even though its kops installing calico.
It ONLY has v1 - and we have working firewall rules - using it:
```
apiVersion: crd.projectcalico.org/v1
kind: NetworkPolicy
metadata:
  name: default.opensearch
#  namespace: {{ .Values.namespace }}
  namespace: graylog
spec:
  order: 100
  selector:
    app.kubernetes.io/name == 'opensearch'
  types:
  - Ingress
  - Egress
  ingress:
  - action: Allow
    protocol: TCP
    destination:
      ports:
      - 9200
  - action: Allow
    protocol: TCP
    destination:
      ports:
      - 9300
      selector: app.kubernetes.io/name == 'opensearch'
  egress:
  - action: Allow
    protocol: TCP
    destination:
      ports:
      - 9300
    source:
      selector: app.kubernetes.io/name == 'opensearch'
```
Above works great - but there is no v3 CRD.. only these in CRD list:
```
k get crds | grep -i network
globalnetworkpolicies.crd.projectcalico.org           2021-10-04T07:37:05Z
globalnetworksets.crd.projectcalico.org               2021-10-04T07:37:05Z
networkpolicies.crd.projectcalico.org                 2021-10-04T07:37:05Z
networksets.crd.projectcalico.org                     2021-10-04T07:37:05Z
```
