### ISSUE TITLE
chown: changing ownership of '/var/cache/squid': Operation not permitted

### ISSUE THREAD

**Issue by riesbl01** [honestica/lifen-charts#84]
Hey everyone, I am getting this error: `chown: changing ownership of '/var/cache/squid': Operation not permitted` when running helm chart in my AKS. I have another team that changed their init container `create-cache-dir` args to:          

```    
      args:
            - |
              set -e
              squid -z 2>&1
```

Would it be possible to either update this helm chart to have these args, provide a solution for why my stuff is failing, or allow the args to be a templated input where I can pass my own args?

**Comment by riesbl01** [comment]
Update: According to https://stackoverflow.com/questions/58747923/write-permissions-on-volume-mount-with-openshift we need to add a security context section under the init container in the deployment yaml, like:

```
      initContainers:
        - name: create-cache-dir
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
              fsGroup: GROUP_ID
```

Not sure what `GROUP_ID` would be so, maybe some suggestions from this team on that? 
https://kubernetes.io/blog/2016/08/security-best-practices-kubernetes-deployment/
